### ISSUE TITLE
I want to upgrade Apache to latest version.

### ISSUE THREAD

**Issue by chiru6003** [joomla-docker/docker-joomla#104]
Currently I am using this .
FROM joomla:php7.3-apache
In the container it is using version.
Server version: Apache/2.4.38 (Debian)
Server built:   2019-10-15T19:53:42

I want to upgrade this Apache version to the latest one.

Please suggest What I have to do. Like changing the image?

Thanks.

**Comment by zero-24** [comment]
Seems we inherit from php:7.3-apache So there is no specific apache version setup here in our docker file.

**Comment by chiru6003** [comment]
Okay then if I go with the latest image Joomla:php.7.4.apache then it installs the latest version of apache? Please suggest how to update the apache version.

**Comment by zero-24** [comment]
As i said we inhertit the php and apache version from the official packages of the PHP Project.

So my suggestion would be to check that upstream file and adjust your file accordingly.

The other way around might could be to upgrade the apache version from your docker file and uninstall the inherited apache version i guess.

**Comment by chiru6003** [comment]
Can you suggest the commands to add my Dockerfile?

**Comment by zero-24** [comment]
I personally can not it might be better to ask in a docker forum where more people with docker knowledge are around.

**Comment by chiru6003** [comment]
Do you have any idea about what Apache version will be installed if I use Joomla:php.7.4-apache?

**Comment by J0WI** [comment]
You can use the `FPM` variant of this image together with the `httpd` image. Then you'll get the latest version of PHP _and_ Apache.

**Comment by beat** [comment]
I believe the answer from JOWI above answers the question, and this issue can be closed by people in power to do so.
