### ISSUE TITLE
Add runtime tests

### ISSUE THREAD

**Issue by J0WI** [joomla-docker/docker-joomla#47]
Many images have custom [runtime tests](https://github.com/docker-library/official-images/tree/master/test/tests), would be great have some too.

**Comment by Llewellynvdm** [comment]
@J0WI are you still interested that we add this?

**Comment by Hackwar** [comment]
php installation/joomla.php

**Comment by Llewellynvdm** [comment]
Yes, we are holding back on J4.3 and will only push out 4.3.1 once its released.
