### ISSUE TITLE
Joolma installation hang on

### ISSUE THREAD

**Issue by khsthomas** [joomla-docker/docker-joomla#54]
I use joomla image:
"Id": "sha256:7d17d5c94cfb56233f6fa05efcbad4881cc13c12ab055fed4521ae3696de75fb"
 ENV JOOMLA_VERSION=3.8.4

Start the docker container:
docker run --name my-joomla --link joomla_db:mysql  -p 9010:80 -d joomla

Open the chrome 
http://localhost:9010
then go the installation.
But it is always hang on 
http://localhost:9010/installation/index.php?view=install
The processing bar never go ahead.

![image](https://user-images.githubusercontent.com/5875042/36715749-88eb8d62-1bd2-11e8-85e6-61747854a0a3.png)

**Comment by J0WI** [comment]
Is this still reproducible with a more recent version?
