### ISSUE TITLE
The instructions in https://hub.docker.com/_/joomla/ don't work. [RANT]

### ISSUE THREAD

**Issue by troindx** [joomla-docker/docker-joomla#77]
This is a rant for you guys, for not being able to do your work properly.

I have simply tried to use docker image joomla-docker, so i've followed all of the instructions provided here:
https://hub.docker.com/_/joomla/
just to try to get a fresh Joomla install working following these instructions only.

surprise surprise, following your instructions  to run it using docker-compose
![image](https://user-images.githubusercontent.com/3263966/57580499-89ff8f00-74aa-11e9-882c-348701287098.png)

and it doesn't work. And it has nothing to do with my setup (I've tried in two different machines, with two different versions of windows and two different tools for docker).
it simply doesn't work, it's incomplete or god knows what the hell but it simply isn't complete.

Following your instructions leaves me here
![image](https://user-images.githubusercontent.com/3263966/57580517-e82c7200-74aa-11e9-8178-2051af720a60.png)

with an error of not being able to connect to the database not even with a SQL explorer tool (I'm using Navicat SQL in this case)

For whatever reason, I feel there is some parameter missing in the database part for this to work. did anyone in your team review these installation instructions?

And then you guys will wonder why WordPress has so many followers. I love Joomla but whenever i program with it or use it sometimes it just feels like talking to an underage 10 y/o  that doesn't fully understand what's going on.

fix this, give proper instructions so that someone can at least install a fresh copy of Joomla and run it in their localhost properly.

**Comment by N6REJ** [comment]
Would you translate the error for me please.

**Comment by N6REJ** [comment]
I agree the directions are completely ambiguous.

**Comment by Sotiris-k** [comment]
What job are you talking about? This is a FOSS project made by a community of **volunteers**.

If something doesn't work, feel free to try and fix it with a PR or whichever way is suited at each occasion.

Your attitude is really not appreciated.

**Comment by troindx** [comment]
how can I fix this? I think you only need to change the stack.yml so that
it properly works out of the box.
get your volunteers to work. Volunteering is a responsibility that has to
be done properly. I volunteered for months rebuilding schools in Nepal
after the earthquake. I don't accept shitty work being done out of
volunteering cos that's not volunteering , it's just filling in. and if a
volunteer does a shitty work then people over the internet get to spend
hours trying to follow an incomplete tutorial that should have taken them 3
minutes

you are right.my attitude is not appreciated, nobody appreciates when the
truth is so hurtful.
SO guess what. * I'm sticking in*. I rant and I'll complain but I will help
to make this something more proper. As soon as I get it to work out of the
box i'll update those instructions.


then if I fail you get to rant about me.

**Comment by wilsonge** [comment]
Well it's not that hard. In your own docker-compose file there you can see the environment variable `JOOMLA_DB_HOST: joomladb` instead of `localhost` in the Joomla host field you need to use `joomladb`

**Comment by troindx** [comment]
man it doesnt work. that will not fix the database problem . the connection
gets rejecTED

**Comment by wilsonge** [comment]
<img width="1010" alt="Screenshot 2019-05-13 at 12 00 21" src="https://user-images.githubusercontent.com/1986000/57616715-bf71ae80-7576-11e9-9848-1c04b93c9f3a.png">

<img width="1440" alt="Screenshot 2019-05-13 at 12 00 54" src="https://user-images.githubusercontent.com/1986000/57616730-ca2c4380-7576-11e9-878b-e640b3d2cf9a.png">

**Comment by wilsonge** [comment]
seems pretty fine to me

**Comment by troindx** [comment]
that seems legit.

**Comment by troindx** [comment]
Ok, I just realized what the problem really was. Thanks to this rant i
managed to understand the problem and i've learned something. I will
further pursue using this image. i just learned I need to learn a little
bit more. I will make a better guide as a way to improve this in a way that
a newbie can easily understand.

with whom will I have to talk to?
thanks by the way. those screenshots were stupidly and ridiculously
helpful. I was using localhost and I wasn't properly understanding what
docker was doing with joomladb as the name.

**Comment by troindx** [comment]
still doesnt work though.
:-(

**Comment by troindx** [comment]
Ok, I think i figured it out.
Joomla wouldnt connect to mysql, whenever i took a look at the services in
my machine i realized
[image: image.png]
There were no ports being redirected.
I tried updating the yml file to add the ports configuration and it worked.

version: '3.1'

services:
  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:5.6
    *ports:*
*      - 3306*
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

Also, it would be nice to indicate in the tutorial to when installing or
configuring, set the user to root and the password to example (in the next
login screen) and remember that host for joomladb is joomladb. Something
like this:

"On installation screen , or when updating configuration.php, remember that
mysql user is root, mysqlpassword is example (in this precise example), and
that the database host is joomladb, "

**Comment by wilsonge** [comment]
You shouldn't have to open port 3306 to the world. It should be accessible between the containers only (which is the same way wordpress' docker links to mysql fwiw). Unsure exactly what's not working on your setup though

**Comment by N6REJ** [comment]
@troindx You ranted at how crappy volunteers we are then by your own admission there's nothing wrong with our code and everything wrong with your actions.  
Think you might want to apologize?

**Comment by troindx** [comment]
but there *is* something wrong!! joomla docker wouldnt connect to joomladb
docker because port isnt exposed. i showed a couple of screenshots and it
is weird that it wouldnt work.

for instance, it would be useful to include volumes for mysl data and
httpdocs folder so that when loading the image with swarm or docker compose
you have access to the joomla files and for them not to get lost when you
reboot the joomla image. cos the database was being saved but the joomla
wasnt for some reason.



its all about making people come closer to docker.
im not complaining about volunteers. im complaining about whomever is
responsible for making all this as user friendly as possible for newbies.
so many people rather simply use wamp in their machines and they r missing
so much in docker.
improve the docs, improve the community. fair and simple. :-)

**Comment by troindx** [comment]
I have made a tutorial about this.
https://www.hamrodev.com/en/app-development/joomla-docker-tutorial
I hope you consider this my way of apologizing, and contributing to make a
small effort to make things easier for noobs like me.
