### ISSUE TITLE
Upgrading Versions

### ISSUE THREAD

**Issue by chris-edwards-pub** [joomla-docker/docker-joomla#87]
What is the best route to upgrading versions?

Upgrade through the admin page then update the docker-compose file to reflect the matching image version?

Thanks,

Chris Edwards

**Comment by Llewellynvdm** [comment]
The best way is to use the Joomla Administrator upgrade path. The images (docker) do not at this time deal with this, and will in fact not override the files or update the database.

I have this in the back of my head... that we would like to add this option to the images as it should not be that hard, should the files and database be persistent to detected that... but nothing has as yet been done to resolve this.

**Comment by jastlw** [comment]
@Llewellynvdm Thx for your response.

Is there a timetable by when the update will be introduced through the Docker image?
Dockerised wordpress can this since its introduction.

I would like to migrate to dockerised Joomla with update option, but waiting for its support.
