### ISSUE TITLE
Problems with permitions in container

### ISSUE THREAD

**Issue by kernusr** [joomla-docker/docker-joomla#90]
Docker runing in Windows 10 Pro
`Docker version 19.03.8, build afacb8b`
`docker-compose version 1.25.4, build 8d51620a`

When I change the setting in the control panel, my application crashes due to an access error

This happens because the volume mounts with root privileges. When I change the setting, the permissions on the file configuration.php set on 0644 and the application cannot read it
How can I solve this problem?

**Comment by Llewellynvdm** [comment]
Please review: https://github.com/joomla-docker/docker-joomla/issues/58#issuecomment-1242735723

This issue has been fixed.
