### ISSUE TITLE
Configuration of Joomla! fails on Azure when attempting to install languages

### ISSUE THREAD

**Issue by CodeOfConduct** [joomla-docker/docker-joomla#94]
Hi,

First of all a big thank you to the developers who created and maintain the Joomla Docker images! 
After successfully deploying the Joomla Docker image PHP7.3 (which I assumed to be v 3.9.19, but discovered is v. 3.9.18 as of the last upload 5 days ago) to an Azure website on azurewebsites.net, the installation of languages and activation of the multilingual feature failed. After selecting "Activate the multilingual feature" = yes on the last configuration page, the following message was displayed:

> Joomla has set en-GB as your default SITE language.
> Joomla has set en-GB as your default ADMINISTRATOR language.

and the multilingual feature is reset to "No". Repeated 2x with the same effect. 
I could successfully complete the installation of Joomla without activation of the feature.

Is that expected behaviour? 

Btw: before I reached the last configuration page,  I had selected 2 languages for installation, but after a wait of several minutes and no progress the language selection page loaded again. When I tried to resubmit it, the error "JINVALID_TOKEN_NOTICE" was displayed. That happened several times before it occurred to me that the error had probably been displayed because the token had expired. After I reduced my selection to just one language, that error did indeed not occur, but the following warning was displayed:

> Joomla was unable to install German DE language. You will be able to install it later using the Joomla! Administrator
> JLIB_INSTALLER_ABORT_NOINSTALLPATH
> COM_INSTALLER_MSG_INSTALL_INVALID_URL
> JLIB_INSTALLER_ERROR_DOWNLOAD_SERVER_CONNECT

 I could proceed to the point mentioned above.

**Comment by CodeOfConduct** [comment]
Following the configuration of the English version of Joomla! 3.9.18 as described above, I discovered that I could upgrade to J! 3.9.19 but not install any additional languages... (tried 3 x). The messages after the failed installation of German-DE were: 

> Warning
> Error connecting to the server: Failed to connect to joomlacode.org port 80: Connection timed out
> Error
> Invalid URL
> Unable to find install package

If anything, I would have expected the Joomla upgrade not to have been possible, rather than the installation of a language pack...
Please let me know, if and how I can contribute to resolving any of the mentioned issues.

**Comment by wilsonge** [comment]
What are your azure NSG rules in Azure? Are they allowing port 80 outbound?

**Comment by CodeOfConduct** [comment]
@wilsonge No NSGs defined in the Azure account in which I deployed Joomla from the Docker image.

**Comment by wilsonge** [comment]
OK Also can you confirm when you tried this. The JoomlaCode server has been a bit flaky recently. We're working on moving the language packs across to the main downloads site to close it down. So it's possible the server was down too. If you tell me when it was I can compare against the server downtime records and just make sure it wasn't as simple as that.

**Comment by CodeOfConduct** [comment]
@wilsonge The first import of the Docker image started at about 15:00 on 15/6 and there was another occasion that started at about 9:00h on 17/6. The configuration of the Joomla instance on azurewebsites.net started at about 15:15 on 17/6, all times are UTC+2.

**Comment by CodeOfConduct** [comment]
Btw, would it be possible to configure the images so that after installation the upload_max_filesize and post_max_size settings are set at a reasonable level in the PHP.INI? I noticed that the max. upload filesize is 2MB after deploying from the Docker image. I'm not sure that this can be changed subsequently...

**Comment by CodeOfConduct** [comment]
Is there anything I can assist with to identify the cause of this issue?

**Comment by Llewellynvdm** [comment]
This should be resolved now.
